apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-service
spec:
  selector:
    app: k8sgpt
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sgpt-rolebinding
subjects:
- kind: ServiceAccount
  name: k8sgpt
roleRef:
  kind: ClusterRole
  name: k8sgpt-cluster-role
  apiGroup: rbac.authorization.k8s.io